### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by viriatusX** [AnimaVillis/ghostflarumintegration#1]
I describe how I have proceeded:

I create a new integration in Ghost and copy the "Admin API key". Then I get the "flarum App key" and when I run the Python script it shows this error:

![CleanShot 2024-01-10 at 22 16 44@2x](https://github.com/AnimaVillis/ghostflarumintegration/assets/64467637/142bd745-7f26-4fea-8568-4c8f7db03c96)

If I replace Admin Api Key for Content Api Key, the error is different:

<img width="908" alt="Captura de pantalla 2024-01-10 a las 22 20 30" src="https://github.com/AnimaVillis/ghostflarumintegration/assets/64467637/0e466ea4-38b2-47ce-90d2-1d560b49332a">

If I launch the script, it generates 1 article at a time, in Flarum, but only the title. No image, no content.

**Comment by AnimaVillis** [comment]
Try install:
pip install requests

And make sure that Your API keys, and links are currect.

**Comment by viriatusX** [comment]
With the latest version, I run the script without errors. In Flarum it creates the latest articles. But inside, empty. It only creates the thread with the title. No text or featured image inside.

**Comment by AnimaVillis** [comment]
> With the latest version, I run the script without errors. In Flarum it creates the latest articles. But inside, empty. It only creates the thread with the title. No text or featured image inside.

Certainly, the script retrieves the ID, title, and link of the article, and it only includes this information. If you desire more data related to the retrieval process, you need to customize the script and function according to your expectations. If you encounter any difficulties with this, please let me know, and I'll assist you in making the necessary adjustments :)

You can check 
https://ghost.org/docs/content-api/#posts - Ghost API Docs
https://docs.flarum.org/rest-api - Flarum API Docs ;)

**Comment by AnimaVillis** [comment]
Open new issue if need ;)
